name: band_space
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^8.2.0
  package_info_plus: ^4.0.2
  file_picker: ^5.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  intl: ^0.18.1
  firebase_storage: ^11.2.6
  mime: ^1.0.4
  just_audio: ^0.9.35
  collection: ^1.17.2
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/launcher_icon.png"
  android: true
  # adaptive_icon_background: "#262830"
  adaptive_icon_foreground: "#262830"  
  image_path_android: "assets/launcher_icon.png"
  ios: true
  image_path_ios: "assets/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
    background_color: "#262830"
    theme_color: "#262830"

flutter_native_splash:
  color: "#262830"
  image: "assets/splash_icon.png"