// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6g_rcFAI6BAHUvgEMQ6OHSLh5o4vZvAA',
    appId: '1:499159965067:web:3fce636b81c7a9482da38e',
    messagingSenderId: '499159965067',
    projectId: 'band-space-prod',
    authDomain: 'band-space-prod.firebaseapp.com',
    storageBucket: 'band-space-prod.appspot.com',
    measurementId: 'G-W5P34ECB5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKUz9TiVhHqTxZ_8HbBM1Qq8gqk5s3tw',
    appId: '1:499159965067:android:03f8d5c4b3cbe7b52da38e',
    messagingSenderId: '499159965067',
    projectId: 'band-space-prod',
    storageBucket: 'band-space-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXjGECDSPAo_ItgwmIyEC5lf6jArJigV0',
    appId: '1:499159965067:ios:11d3a8be529a2e862da38e',
    messagingSenderId: '499159965067',
    projectId: 'band-space-prod',
    storageBucket: 'band-space-prod.appspot.com',
    iosBundleId: 'lislav.bandspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXjGECDSPAo_ItgwmIyEC5lf6jArJigV0',
    appId: '1:499159965067:ios:b97eeff3ae6f99b52da38e',
    messagingSenderId: '499159965067',
    projectId: 'band-space-prod',
    storageBucket: 'band-space-prod.appspot.com',
    iosBundleId: 'com.example.bandSpace.RunnerTests',
  );
}
